//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotType
    {
        public SlotType()
        {
            this.Slots = new HashSet<Slot>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal PricePerMinute { get; set; }
    
        public virtual ICollection<Slot> Slots { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
