//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingLot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public Slot()
        {
            this.VehicleSlots = new HashSet<VehicleSlot>();
        }
    
        public int Id { get; set; }
        public int SlotTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ReservationTypeId { get; set; }
    
        public virtual SlotType SlotType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<VehicleSlot> VehicleSlots { get; set; }
        public virtual ReservationType ReservationType { get; set; }
    }
}
